/*
SQLyog 企业版 - MySQL GUI v8.14 
MySQL - 5.6.40 : Database - subject
*********************************************************************
*/


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 导出 examdb 的数据库结构
CREATE DATABASE IF NOT EXISTS `subject` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `subject`;


/*Table structure for table `TB_SUBJECT` */

DROP TABLE IF EXISTS `TB_SUBJECT`;
CREATE TABLE `TB_SUBJECT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `COL_SUBJECT_CONTENT` varchar(255) NOT NULL,
  `COL_SUBJECT_DB_ID` int(11) NOT NULL,
  `COL_SUBJECT_TYPE` int(11) DEFAULT NULL COMMENT '0:判断题\n1:单选题\n2:多选题',
  `COL_DEFFICULTY_WEIGHT` int(11) NOT NULL DEFAULT '0' COMMENT '题目难度系数0~100，系数越高说明题目越难',
  `COL_IS_OPEN` int(11) NOT NULL DEFAULT '1' COMMENT '0:关闭\n1:打开',
  `COL_CREATE_TIME` bigint(11) NOT NULL,
  `COL_UPDATE_TIME` bigint(11) DEFAULT NULL,
  `COL_CREATOR_ID` char(9) DEFAULT NULL,
  `COL_UPDATER_ID` char(9) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UDX_DB_ID_AND_CONTENT` (`COL_SUBJECT_CONTENT`,`COL_SUBJECT_DB_ID`),
  KEY `IDX_SUBJECT_CONTENT` (`COL_SUBJECT_CONTENT`),
  KEY `IDX_SUBJECT_TYPE` (`COL_SUBJECT_TYPE`),
  KEY `IDX_IS_OPEN` (`COL_IS_OPEN`),
  KEY `IDX_CREATE_TIME` (`COL_CREATE_TIME`),
  KEY `IDX_UPDATE_TIME` (`COL_UPDATE_TIME`),
  KEY `IDX_CREATEOR_ID` (`COL_CREATOR_ID`),
  KEY `IDX_UPDATER_ID` (`COL_UPDATER_ID`),
  KEY `IDX_DEFFICULTY_WEIGHT` (`COL_DEFFICULTY_WEIGHT`),
  KEY `IDX_SUBJECT_DB_ID` (`COL_SUBJECT_DB_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=109 DEFAULT CHARSET=utf8;

/*Data for the table `TB_SUBJECT` */

/*Table structure for table `TB_SUBJECT_ANSWER` */

DROP TABLE IF EXISTS `TB_SUBJECT_ANSWER`;

CREATE TABLE `TB_SUBJECT_ANSWER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `COL_SUBJECT_ID` int(11) NOT NULL,
  `COL_SUBJECT_ANSWER` int(11) NOT NULL COMMENT '以二进制位移方式标志ORDER，来适配判断、单选、多选等情况，举例多选说明：\nA:1-->0001\nB:2-->0010\nC:4-->0100\nD:8-->1000\n正确答案是CD，那么对应的正确答案是1100，也就是12',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UDX_SUBJECT_ID` (`COL_SUBJECT_ID`),
  KEY `IDX_SUBJECT_ANSWER` (`COL_SUBJECT_ANSWER`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=latin1;

/*Data for the table `TB_SUBJECT_ANSWER` */

/*Table structure for table `TB_SUBJECT_DB` */

DROP TABLE IF EXISTS `TB_SUBJECT_DB`;

CREATE TABLE `TB_SUBJECT_DB` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `COL_SUBJECT_DB_NAME` varchar(45) NOT NULL,
  `COL_SUBJECT_DB_DESC` varchar(45) DEFAULT NULL,
  `COL_IS_OPEN` int(11) NOT NULL DEFAULT '1' COMMENT '0:关闭\n1:打开',
  `COL_CREATE_TIME` bigint(11) NOT NULL,
  `COL_UPDATE_TIME` bigint(11) DEFAULT NULL,
  `COL_CREATOR_ID` char(9) NOT NULL,
  `COL_UPDATER_ID` char(9) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UDX_COL_SUBJECT_DB_NAME` (`COL_SUBJECT_DB_NAME`),
  KEY `IDX_SUBJECT_DB_DESC` (`COL_SUBJECT_DB_DESC`),
  KEY `IDX_IS_OPEN` (`COL_IS_OPEN`),
  KEY `IDX_CREATE_TIME` (`COL_CREATE_TIME`),
  KEY `IDX_UPDATE_TIME` (`COL_UPDATE_TIME`),
  KEY `IDX_CREATOR_ID` (`COL_CREATOR_ID`),
  KEY `IDX_UPDATER_ID` (`COL_UPDATER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

/*Data for the table `TB_SUBJECT_DB` */

insert  into `TB_SUBJECT_DB`(`ID`,`COL_SUBJECT_DB_NAME`,`COL_SUBJECT_DB_DESC`,`COL_IS_OPEN`,`COL_CREATE_TIME`,`COL_UPDATE_TIME`,`COL_CREATOR_ID`,`COL_UPDATER_ID`) values (7,'信息安全考试2','信息安全考试2',1,20180716140340,0,000007910,0);

/*Table structure for table `TB_SUBJECT_ITEM` */

DROP TABLE IF EXISTS `TB_SUBJECT_ITEM`;

CREATE TABLE `TB_SUBJECT_ITEM` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '{DISPLAY:ITEM_ID}',
  `COL_SUBJECT_ID` int(11) NOT NULL,
  `COL_OPTION_CONTENT` varchar(100) NOT NULL,
  `COL_OPTION_ORDER` int(11) NOT NULL DEFAULT '0' COMMENT '以二进制位移方式标志ORDER，来适配判断、单选、多选等情况，举例多选说明：\nA:1-->0001\nB:2-->0010\nC:4-->0100\nD:8-->1000\n正确答案是CD，那么对应的正确答案是1100，也就是12\n',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=141 DEFAULT CHARSET=utf8;

/*Data for the table `TB_SUBJECT_ITEM` */

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
