spring:
  profiles: docker
  application:
    name: api-gateway

# 配置运行端口号
server:
  port: 8765

# 注册中心配置
eureka:
  instance:
      hostname: localhost
      port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

# zull 配置
zuul:
  routes:
    admin-service: /admin/**
    exam-service: /exam/**
    auth:
      path: /auth/**
      url: http://localhost:8769/auth/
      sensitive-headers:

security:
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: http://localhost:8765/auth/oauth/token
      userAuthorizationUri: http://localhost:8765/auth/oauth/authorize
      clientId: web-app
      preEstablishedRedirectUri: http://localhost:8765/login
      registeredRedirectUri: http://localhost:8765/login
      useCurrentUri: false

    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAimUKhvBhsoeSM3HkIOP/Y3RXjvonBlZnLj8oO92TyAKG53lmAoK0wZ5MTZPsfrOz2Z7CeAp6mPhUANX2RUoFwVzG7rJmgWyqGmGFNBmtYL+uVqQ80TzWi5zyzXTxgVMWiCqqw/u4AeE1qhN8chnGwhUBnpgPAPd8v57mIwg0n5JxjdYe7pgHlpvt8ZXTXd1KBxB5K7WjNlCfMf75ZEeBaplxsSfJUwKbnHQKWcY3NnpjkVR8y4jviAbkOHmGMaliM7fcsLzbosBUPDQuNlvYdjPBRfH6MMPeXRW6On3u0Um9wIYmkQS+AEgHCq4UuLOnTTqqxnGkwFYeMAAXmRyMtQIDAQAB
          -----END PUBLIC KEY-----

#logback配置，生产环境日志级别为 WARN 甚至更高
logging:
  file: logs/api-gateway/api-gateway-docker.log
  level:
    root: WARN