server:
  port: 8877

spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: true
      server:
        health:
          enabled:  false
        native:
          searchLocations: D:/Utils_doc/config_test
  profiles:
    active: native
# 注册中心配置
eureka:
  instance:
      hostname: localhost
      port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/